mapping:
- attribute: 车道线真值-隧道
  id: 0
  name: 车道线真值-隧道
- attribute: TSLR真值-限速牌
  id: 1
  name: TSLR真值-限速牌
- attribute: TSLR真值-文字路牌
  id: 2
  name: TSLR真值-文字路牌
- attribute: TSLR真值-指示标志（左右掉头环岛等）
  id: 3
  name: TSLR真值-指示标志（左右掉头环岛等）
- attribute: TSLR真值-提示类标志
  id: 4
  name: TSLR真值-提示类标志
- attribute: TSLR真值-禁止类标志
  id: 5
  name: TSLR真值-禁止类标志
- attribute: TSLR真值-注意行人/注意儿童
  id: 6
  name: TSLR真值-注意行人/注意儿童
- attribute: TSLR真值-限制类标志（高宽重）
  id: 7
  name: TSLR真值-限制类标志（高宽重）
- attribute: TSLR真值-路口红绿灯
  id: 8
  name: TSLR真值-路口红绿灯
- attribute: TSLR真值-注意左侧合流/注意右侧合流
  id: 9
  name: TSLR真值-注意左侧合流/注意右侧合流
- attribute: TSLR真值-施工标志/向左改道/向右改道/向左右改道
  id: 10
  name: TSLR真值-施工标志/向左改道/向右改道/向左右改道
- attribute: TSLR真值-停车让行/减速让行
  id: 11
  name: TSLR真值-停车让行/减速让行
- attribute: TSLR真值-解除限速牌
  id: 12
  name: TSLR真值-解除限速牌
- attribute: GOP真值-特定类-动物
  id: 13
  name: GOP真值-特定类-动物
- attribute: TSLR真值-车道合流/车道减少
  id: 14
  name: TSLR真值-车道合流/车道减少
- attribute: TSLR真值-公交车道
  id: 15
  name: TSLR真值-公交车道
- attribute: TSLR真值-解除限速类-以0结尾
  id: 16
  name: TSLR真值-解除限速类-以0结尾
- attribute: TSLR真值-路面标识
  id: 17
  name: TSLR真值-路面标识
- attribute: TSLR真值-限速类-以0结尾（含电子限速）
  id: 18
  name: TSLR真值-限速类-以0结尾（含电子限速）
- attribute: GOP真值-一般类-隔离柱
  id: 19
  name: GOP真值-一般类-隔离柱
- attribute: TSLR真值-80m-TSR
  id: 20
  name: TSLR真值-80m-TSR
- attribute: TSLR真值-匝道标志
  id: 21
  name: TSLR真值-匝道标志
- attribute: TSLR真值-120m-TLR
  id: 22
  name: TSLR真值-120m-TLR
- attribute: GOP真值-一般类-护栏
  id: 23
  name: GOP真值-一般类-护栏
- attribute: TSLR真值-限速类-以5结尾（含电子限速）
  id: 24
  name: TSLR真值-限速类-以5结尾（含电子限速）
mode: one
